stages:
  - test
  - publish

image: rust:latest

test:
  stage: test
  script:
    - cargo build
    - cargo test

publish:
  stage: publish
  script:
    - chmod +x check_diff_ver.sh
    - |
      if ./check_diff_ver.sh clap_serde_proc/Cargo.toml
      then
        cargo publish -p clap-serde-proc
      fi
    - |
      if ./check_diff_ver.sh Cargo.toml
      then
        cargo publish
      fi
  only:
    refs: [tags]
